### ISSUE TITLE
Dls 24

### ISSUE THREAD

**Issue by ROONALDOIRAN** [theshinramen/DLS-Card-Creator#4]
![20231204_211302](https://github.com/theshinramen/DLS-Card-Creator/assets/152903092/3acd5e84-8d11-42d6-a0e6-5bb151938622)
![20231204_211351](https://github.com/theshinramen/DLS-Card-Creator/assets/152903092/567c8edb-9510-440b-b87c-1a68e19ea7da)
![20231204_211358](https://github.com/theshinramen/DLS-Card-Creator/assets/152903092/863f58aa-2fff-490a-a187-6b3e743cae91)

**Comment by Yjjaiyrr** [comment]
cool

**Comment by Yjjaiyrr** [comment]
4

**Comment by Yjjaiyrr** [comment]
![1735050271095](https://github.com/user-attachments/assets/aefdae5b-735a-491a-ae0a-bc41ede8572b)
YOSEF
